import { BlogItem } from "./blog.types";

export const ALL_BLOGS: BlogItem[] = [
  {
    id: "1",
    title: "Getting Started with React Hooks",
    excerpt:
      "Learn how to use React Hooks to manage state and side effects in functional components.",
    author: "John Doe",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "2 days ago",
    publishedOn: "2026-02-20",
    readMinutes: 5,
    category: "React",
    likes: 245,
    comments: 32,
    views: 1200,
  },
  {
    id: "2",
    title: "The Future of Web Development",
    excerpt:
      "Exploring emerging technologies and trends that will shape web development in 2026.",
    author: "Jane Smith",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "4 days ago",
    publishedOn: "2026-02-18",
    readMinutes: 8,
    category: "Web Dev",
    likes: 512,
    comments: 78,
    views: 2500,
  },
  {
    id: "3",
    title: "TypeScript Best Practices",
    excerpt:
      "Master TypeScript with practical patterns that keep large apps maintainable.",
    author: "Mike Johnson",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "1 week ago",
    publishedOn: "2026-02-15",
    readMinutes: 10,
    category: "TypeScript",
    likes: 389,
    comments: 56,
    views: 1800,
  },
  {
    id: "4",
    title: "CSS Grid Advanced Layouts",
    excerpt:
      "Create complex responsive layouts with CSS Grid while keeping your stylesheet clean.",
    author: "Sarah Lee",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "5 days ago",
    publishedOn: "2026-02-17",
    readMinutes: 7,
    category: "CSS",
    likes: 267,
    comments: 41,
    views: 950,
  },
  {
    id: "5",
    title: "Mastering Node.js Streams",
    excerpt:
      "Handle large data flows efficiently and build scalable processing pipelines.",
    author: "David Park",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "3 days ago",
    publishedOn: "2026-02-19",
    readMinutes: 12,
    category: "Node.js",
    likes: 445,
    comments: 67,
    views: 2100,
  },
  {
    id: "6",
    title: "Next.js App Router Deep Dive",
    excerpt:
      "Understand nested layouts, loading states, and server components in Next.js.",
    author: "Emily Chen",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "1 day ago",
    publishedOn: "2026-02-21",
    readMinutes: 9,
    category: "Next.js",
    likes: 678,
    comments: 92,
    views: 3200,
  },
  {
    id: "7",
    title: "Python Data Analysis with Pandas",
    excerpt:
      "Use Pandas for fast data cleaning, aggregation, and exploratory analysis workflows.",
    author: "Alex Rivera",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "6 days ago",
    publishedOn: "2026-02-16",
    readMinutes: 11,
    category: "Python",
    likes: 523,
    comments: 74,
    views: 2700,
  },
  {
    id: "8",
    title: "GraphQL vs REST APIs",
    excerpt:
      "Compare API styles to choose the right contract for your frontend and backend teams.",
    author: "Rachel Gold",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "3 days ago",
    publishedOn: "2026-02-19",
    readMinutes: 6,
    category: "API",
    likes: 412,
    comments: 58,
    views: 1600,
  },
  {
    id: "9",
    title: "Design Systems for Product Teams",
    excerpt:
      "Build reusable UI foundations that improve consistency and shipping speed.",
    author: "Priya Nair",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "2 weeks ago",
    publishedOn: "2026-02-08",
    readMinutes: 14,
    category: "Design",
    likes: 296,
    comments: 39,
    views: 1210,
  },
  {
    id: "10",
    title: "Build Better APIs with Validation",
    excerpt:
      "Use schema validation and contract-first techniques to reduce production bugs.",
    author: "John Doe",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "10 days ago",
    publishedOn: "2026-02-12",
    readMinutes: 8,
    category: "Backend",
    likes: 334,
    comments: 44,
    views: 1435,
  },
  {
    id: "11",
    title: "State Management Patterns in 2026",
    excerpt:
      "A practical comparison of modern React state management approaches.",
    author: "Emily Chen",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "12 days ago",
    publishedOn: "2026-02-10",
    readMinutes: 9,
    category: "React",
    likes: 451,
    comments: 51,
    views: 1755,
  },
  {
    id: "12",
    title: "Practical Caching with Redis",
    excerpt:
      "Improve response times with cache-aside and expiration strategies that scale.",
    author: "David Park",
    authorImage: "/images/author.avif",
    coverImage: "/images/bg.avif",
    publishedAt: "20 days ago",
    publishedOn: "2026-02-02",
    readMinutes: 7,
    category: "Performance",
    likes: 381,
    comments: 36,
    views: 1990,
  },
];